# generate new triples based on existing ones
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX cim: <https://sites.google.com/site/ontology2013/cim/>
PREFIX imm: <http://www.semanticweb.org/ontologies/2013/immutable#>
CONSTRUCT   {?i rdf:type imm:immutable}
WHERE       {?i cim:Writeable "false"^^xsd:boolean}