# Show the triples related to the item with given name
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX cim: <https://sites.google.com/site/ontology2013/cim/>
DESCRIBE ?x
WHERE { ?x cim:Name "r:\\test\\test_file"^^xsd:normalizedString }