# List all the items in the directory with given name
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX cim: <https://sites.google.com/site/ontology2013/cim/>
SELECT ?fname
  WHERE {
    ?file cim:Name ?fname.
    ?dcf cim:PartComponent ?file.
    ?dcf cim:GroupComponent ?folder.
    ?folder cim:Name "r:"^^xsd:normalizedString
  }