PREFIX tgm: <https://sites.google.com/site/trigram/>
SELECT ?filename ?checksum
WHERE {
  {
    SELECT ?checksum
    WHERE {?file tgm:md5 ?checksum}
    GROUP BY ?checksum HAVING (COUNT(*) > 1)
  }
  ?file tgm:md5 ?checksum .
  ?file tgm:name ?filename
}