PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dir: <https://sites.google.com/site/ontology2013/tgmdir.owl#>
SELECT ?name
    WHERE { ?parent_id dir:contain ?node_id .
            ?parent_id dir:name "trigram"^^xsd:normalizedString .
            ?node_id dir:name ?name . }