PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX cim: <https://sites.google.com/site/ontology2013/cim/>
SELECT ?dirname
  WHERE {
    ?dir cim:Name ?dirname.
    ?dir rdf:type cim:CIM_Directory.
    ?dcf cim:GroupComponent ?dir.
    FILTER NOT EXISTS {?dcf cim:PartComponent ?somefile}
  }