# List all the items in the directory with given name
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX tgm: <https://sites.google.com/site/trigram/>
SELECT ?fileName
  WHERE {
    ?file tgm:name ?fileName .
    ?dir tgm:contains ?file .
    ?dir tgm:name "e:\\download\\autoit"^^xsd:normalizedString
  }