#!/usr/bin/env bash

cygwin=false

case "`uname`" in
  CYGWIN*) cygwin=true;;
  Darwin) darwin=true;;
esac

if $cygwin; then
  CP=`cat .classpath | grep 'kind="lib"' | awk -F '"' '{printf"%s;",$2}'`
  scala -cp "$CP;target/scala-2.10/classes" TrigramTranslator "$@" 
else
  CP=`cat .classpath | grep 'kind="lib"' | awk -F '"' '{printf"%s:",$2}'`
  scala -cp "$CP:target/scala-2.10/classes" TrigramTranslator "$@" 
fi
