#!/usr/bin/env bash

cygwin=false

case "`uname`" in
  CYGWIN*) cygwin=true;;
  Darwin) darwin=true;;
esac

export TGM_ROOT=$(dirname `which $0`)
# export TGM_DATA=$TGM_ROOT/data
CP=`ls -1 $TGM_ROOT/target/scala-2.10/lib | sed 's/*//g' | awk -v tr="$TGM_ROOT" '{printf tr"/target/scala-2.10/lib/"$1":"}'`
CP=$CP$TGM_ROOT:$TGM_ROOT/target/scala-2.10/classes

if $cygwin; then
  CP=`cygpath -alpm $CP`
  TGM_ROOT=`cygpath -alm $TGM_ROOT`
fi

# export TGM_DATA=r:/data

scala -J-Xmx2g -cp "$CP" Trigram "$@" 
