#!/bin/sh
# trigram launcher script
# use .classpath to load dependencies
# use relative directory to load compiled classes
CLASSLIB=`cat .classpath | grep 'kind="lib"' | awk -F '"' '{printf"%s;",$2}'`
scala -cp "$CLASSLIB;target/scala-2.10/classes" trigram "$@" 
